routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\AppController::class, 'landing'])->middleware([
    'statistic'
])->name('home');


Route::get('/tags/{tag_slug}', [\App\Http\Controllers\TagController::class, 'index'])->name('tag.explore');

Route::prefix('/{category_slug}')
->middleware([
    'statistic'
])
->name('category.')
->group(function(){
    Route::get('/', [\App\Http\Controllers\CategoryController::class, 'index'])->name('explore');


    Route::get('/{post_slug}', [\App\Http\Controllers\CategoryController::class, 'post_show'])->name('post.show');
});

resources/views/layouts/app.blade.php
@extends('layouts.base')

<!-- Header Section -->
@section('header')

    <nav class="h-20 w-full fixed top-0 bg-white dark:bg-zinc-800 flex justify-center shadow z-50" x-data="mobileSidebarUtilities()">
        <div class="w-full max-w-6xl flex justify-between items-center h-full px-4">
            <figure class="relative h-full">
                <img src="{{ theme_asset('images/logo-colored.png') }}" alt="Site Logo" class="h-full">
                <a href="{{ route('home', [
                        'utm_content' => 'navigation-logo-click'
                    ]) }}" class="absolute inset-0"></a>
            </figure>
            <div class="hidden lg:flex items-center justify-start gap-3">
                @foreach($categories as $category)
                    <div class="relative text-primary-500 font-bold">
                        {{ $category->name }}
                        <a href="{{ route('category.explore', [
                                'category_slug' => $category->slug,
                                'utm_content' => 'navigation-logo-click'
                            ]) }}" class="absolute inset-0">
                        </a>
                    </div>
                @endforeach
                @livewire('search-component')
            </div>
            <button class="lg:hidden p-2 rounded-md" @click="show_sidebar_container = true" @click.debounce.500="show_sidebar_content = true">
                @svg('heroicon-o-menu', 'w-10 h-10 text-primary-500')
            </button>
        </div>
        @include('components.slide-over')
    </nav>

@endsection
<!-- End Header Section -->

@section('hero')
    <figure class="w-full mt-20 relative">
        <img src="@yield('hero-banner', theme_asset('images/banner.jpg'))" 
        class="w-full h-96 object-cover"
        alt="@yield('hero-banner-alt', 'Hero Banner')">
        <div class="absolute inset-0 flex flex-col justify-center items-center bg-gradient-to-r from-pink-400/50 via-purple-400/50 to-primary-500/50  gap-3 px-3 backdrop-blur-sm">
            <div class="w-full max-w-md py-6 px-7 bg-primary-500 bg-opacity-30 flex justify-center items-center">
                <h1 class="text-xl lg:text-4xl text-white font-bold text-center">
                    @yield('hero-header')
                </h1>
            </div>
            <p class="text-md lg:text-lg font-bold text-white max-w-md text-center">
                @yield('hero-content')
            </p>
        </div>
    </figure>
    
@endsection

<!--  Body Section -->
@section('body')
    <div class="flex flex-col lg:flex-row gap-3">
        <div class="w-full lg:w-3/4">
            @yield('app-content')
        </div>
        <div class="w-full lg:w-1/4 lg:py-5">
            <div class="sticky top-24 space-y-4">
                @if($tags)
                    <div class="px-2 py-3 rounded-lg bg-white border space-y-2" data-card-type="Post tag card">
                        <h1 class="text-md">
                            Tags
                        </h1>
                        <div class="flex gap-3 flex-wrap max-h-32 overflow-y-auto scrollbar-thin scrollbar-thumb-primary scrollbar-track-primary-300">
                            @foreach($tags as $tag)
                                @include('components.tag-item', ['tag' => $tag])
                            @endforeach
                        </div>
                    </div>
                @endif

                @include('components.share-card')
            </div>
        </div>
    </div>
@endsection
<!-- End Body Section -->

@push('scripts')
    <script>
        function mobileSidebarUtilities()
        {
            return {
                show_sidebar_container : false,
                show_sidebar_content : false,
            };
        }
    </script>
@endpush

resources/views/layouts/base.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="bg-gray-200 scroll-smooth scrollbar-thin scrollbar-thumb-primary scrollbar-track-primary-300">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        @hasSection('title')

            <title>@yield('title') - {{ config('app.name') }}</title>
        @else
            <title>{{ config('app.name') }}</title>
        @endif

        {!! SEO::generate(true) !!}

        <!-- Favicon -->
		<link rel="shortcut icon" href="@yield('favicon', theme_asset('images/logo-colored.png'))">

        <!-- Fonts -->
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ theme_asset('css/app.css') }}">
        @livewireStyles
        <style>
            [x-cloak] { display: none !important; }
        </style>
        @toastScripts
        <!-- Scripts -->
        <script src="{{ theme_asset('js/app.js') }}" defer></script>

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        @stack('google-ads')

    </head>

    <body>
        <livewire:toasts />
        @yield('header')

        @yield('hero')

        <div class="w-full max-w-6xl mx-auto px-2 lg:px-4">
            @yield('body')

            <footer class="text-center font-semibold opacity-30 relative">
                Code With Diki - CMS {{ "@".now()->format('Y') }}
                <a href="https://codewithdiki.com" class="absolute inset-0"></a>
            </footer>
        </div>

        @livewireScripts
        

        @stack('scripts')

        @yield('google-analytics')
    </body>
</html>